title: "Graphia"
author: © 2020-2025 Tim Angus, Tom Freeman
logo: "/assets/logo-hires.png"
email: info@graphia.app
description: Visualisation tool for the creation and analysis of large graphs.

lang: en_GB

url: "https://graphia.app"

github_username: graphia-app
github_project: graphia-app/graphia

theme: minima

header_pages:
  - download.md
  - example-data.md
  - userguide.md

google_analytics: G-VRMV9XLYXB

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

downloads:
  windows: "https://github.com/graphia-app/graphia/releases/download/5.1/Graphia-5.1-installer.exe"
  macos: "https://github.com/graphia-app/graphia/releases/download/5.1/Graphia-5.1.dmg"
  linux: "https://github.com/graphia-app/graphia/releases/download/5.1/Graphia-5.1.tar.gz"
  release: "https://github.com/graphia-app/graphia/releases/tag/5.1"
  source: "https://github.com/graphia-app/graphia/tree/5.1"
