title: "Graphia"
author: © 2020 Graphia Technologies Ltd.
logo: "/assets/logo-hires.png"
email: info@graphia.app
description: Graphia is a visualisation tool for the creation and analysis of graphs.

lang: en_GB

baseurl: ""
url: "https://graphia.app"

github_username: graphia-app
slack_instancename: graphia

theme: minima

header_pages:
  - download.md
  - example-data.md
  - userguide.md

google_analytics: UA-164944155-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

downloads:
  windows: "https://github.com/graphia-app/graphia/releases/download/2.0/Graphia-2.0-installer.exe"
  macos: "https://github.com/graphia-app/graphia/releases/download/2.0/Graphia-2.0.dmg"
  linux: "https://github.com/graphia-app/graphia/releases/download/2.0/Graphia-2.0.tar.gz"
  source: "https://github.com/graphia-app/graphia/tree/2.0"
